# -*- coding: utf-8 -*-
"""question-0001-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzSanKu6vS9pghE9nrQ_amaUFY0oSTtE
"""

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score


# =====================================================
# FASE 1 - PASO 2: GENERADOR DE CASOS DE USO
# =====================================================

def generar_caso_uso_evaluar_modelo():
    """
    Genera un caso de prueba aleatorio para la función evaluar_modelo_estratificado
    """

    np.random.seed()

    # ---------------------------------------------------
    # 1. Generar datos aleatorios
    # ---------------------------------------------------
    n_samples = np.random.randint(50, 120)
    n_features = np.random.randint(3, 8)

    X = np.random.randn(n_samples, n_features)

    # Variable binaria desbalanceada
    y = np.random.choice([0, 1], size=n_samples, p=[0.7, 0.3])

    columns = [f"feature_{i}" for i in range(n_features)]
    X_df = pd.DataFrame(X, columns=columns)

    n_splits = np.random.randint(3, 7)

    # ---------------------------------------------------
    # 2. Calcular OUTPUT esperado (ground truth)
    # ---------------------------------------------------

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_df)

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

    acc_scores = []
    f1_scores = []

    for train_idx, test_idx in skf.split(X_scaled, y):
        X_train, X_test = X_scaled[train_idx], X_scaled[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        model = LogisticRegression()
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        acc_scores.append(accuracy_score(y_test, y_pred))
        f1_scores.append(f1_score(y_test, y_pred))

    expected_output = {
        "accuracy_promedio": float(np.mean(acc_scores)),
        "f1_promedio": float(np.mean(f1_scores))
    }

    # ---------------------------------------------------
    # 3. Construir INPUT
    # ---------------------------------------------------

    inputs = {
        "X": X_df.copy(),
        "y": y.copy(),
        "n_splits": n_splits
    }

    return inputs, expected_output


# =====================================================
# FASE 1 - PASO 3: PRUEBA DEL GENERADOR
# =====================================================

if __name__ == "__main__":

    inputs, expected = generar_caso_uso_evaluar_modelo()

    print("======== INPUTS ========")
    for k, v in inputs.items():
        print(f"{k}:\n{v}\n")

    print("======== EXPECTED OUTPUT ========")
    print(expected)