# -*- coding: utf-8 -*-
"""answer-0711.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSG_J2uWUkT_bfXgapWXiK8KHHs-BwqP
"""

import pandas as pd


def calcular_totales(df: pd.DataFrame, categoria: str) -> pd.DataFrame:
    """
    Filtra el DataFrame por categoría, calcula el total (cantidad * precio_unitario)
    y devuelve las columnas relevantes con índice reiniciado.
    """
    resultado = df[df['categoria'] == categoria].copy()
    resultado['total'] = resultado['cantidad'] * resultado['precio_unitario']
    return resultado[['producto', 'cantidad', 'precio_unitario', 'total']].reset_index(drop=True)