# -*- coding: utf-8 -*-
"""answer-0875.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcTPsYXzpIItGSBAScXDyfiCsXyLb_-z
"""

import pandas as pd


def estadisticas_por_cliente(df: pd.DataFrame) -> pd.DataFrame:
    """
    Agrupa por cliente y calcula monto_promedio, monto_maximo y total_transacciones.
    Devuelve el resultado ordenado descendentemente por total_transacciones,
    con 'cliente' como índice.
    """
    resultado = df.groupby('cliente').agg(
        monto_promedio=('monto', 'mean'),
        monto_maximo=('monto', 'max'),
        total_transacciones=('num_transacciones', 'sum')
    )
    resultado['monto_promedio'] = resultado['monto_promedio'].round(2)
    resultado['monto_maximo'] = resultado['monto_maximo'].round(2)
    return resultado.sort_values('total_transacciones', ascending=False)